In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# gauss-jordan method
def gauss_jordan(a, b):
    n = len(b)
    
    # elimination phase
    #loops the row of the matrix
    for k in range(0, n - 1):
        #loops the values in the ith row (column values)
        for i in range(k+1, n):
            # Making the upper triangle, by altering some of the values in a for loop. the lower part will become 0.
            if a[i,k] != 0.0:
                lam  = a[i,k]/a[k,k]
                a[i,k+1:n] -= lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
    # back substitution
    for k in range(n-1, -1, -1):
        b[k] = (b[k] - np.dot(a[k,k+1:n], b[k+1:n]))/a[k,k]
    return b

def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a [i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    return a

     
def LUsolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k],b[0:k])
        b[n-1] = b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [3]:
a = np.array([[3,-1],[2,1]], dtype = float)
b = np.array([[7],[8]], dtype = float)
x = gauss_jordan(a, b)
print(x)

[[3.]
 [2.]]


The Process of Gauss-Elimination
$
The matrix 
$

In [4]:
dim = int(input("Input how many dimensions"))
lhs = []
rhs = []
for i in range(dim):
    lhs.append([])
nums = int(input('How many values in a row'))
for k in range(dim):
    for j in range(nums):
        val = int(input('Input value'))
        lhs[k].append(val)
for l in range(dim):
    val = int(input('Input value'))
    rhs.append(val)
lhs_input = np.array(lhs,dtype= float)
rhs_input = np.array(rhs,dtype = float)
 

Input how many dimensions2
How many values in a row2
Input value3
Input value-1
Input value2
Input value1
Input value7
Input value8


###### 

In [5]:
lhs_input

array([[ 3., -1.],
       [ 2.,  1.]])

In [6]:
rhs_input

array([7., 8.])

In [7]:
gauss_jordan(lhs_input, rhs_input)

array([3., 2.])

In [8]:
dim = int(input("Input how many dimensions"))
lhs = []
rhs = []
for i in range(dim):
    lhs.append([])
nums = int(input('How many values in a row'))
for k in range(dim):
    for j in range(nums):
        val = int(input('Input value'))
        lhs[k].append(val)
for l in range(dim):
    val = int(input('Input value'))
    rhs.append(val)
lhs_input = np.array(lhs,dtype= float)
rhs_input = np.array(rhs,dtype = float)



Input how many dimensions2
How many values in a row2
Input value3
Input value-1
Input value2
Input value1
Input value7
Input value8


In [9]:
LUdecomp(lhs_input)

array([[ 3.        , -1.        ],
       [ 0.66666667,  1.66666667]])

In [11]:
LUsolve(lhs_input,rhs_input)

array([3., 2.])